# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 387c143da8aca8e286842971c4a803ac943754ceaddfa3d45512ba547d094a7c6d9ec7ef1580da7df962d6619092f9bd31190677a96b47922e4511252aab33c9

test:
  secret_key_base: f73121380a8a8692d0fa484644dfe19af7cf216f200f1500dda9ea75b9f848e8a76832d4f08a4feeb92c69dd177fa8abf6fd12dafe353aee0c52aa721caa206d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
